# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - scaled_joint_trajectory_controller
    - gripper_action_controller

  scaled_joint_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    action_ns: follow_joint_trajectory
    default: true
    
  gripper_action_controller:
    type: ParallelGripperCommand
    joints:
      - gripper_robotiq_hande_left_finger_joint
      - gripper_robotiq_hande_right_finger_joint
    action_ns: gripper_cmd
    default: true