planning_plugins:
  - ompl_interface/OMPLPlanner
  
# planner_configs:
#   RRTConnectkConfigDefault:
#     type: geometric::RRTConnect
#     range: 0.05
#     goal_bias: 0.05
#     max_planning_time: 5.0

# The order of the elements in the adapter corresponds to the order they are processed by the motion planning pipeline.
request_adapters:
  - default_planning_request_adapters/ResolveConstraintFrames
  - default_planning_request_adapters/ValidateWorkspaceBounds
  - default_planning_request_adapters/CheckStartStateBounds
  - default_planning_request_adapters/CheckStartStateCollision
response_adapters:
  - default_planning_response_adapters/AddTimeOptimalParameterization
  - default_planning_response_adapters/ValidateSolution
  - default_planning_response_adapters/DisplayMotionPath