scene_objects:
  - id: "table"
    shape: "box"
    position: [0.5, 0.0, -0.05]
    quat_xyzw: [0.0, 0.0, 0.0, 1.0]
    dimensions: [0.5, 1.0, 0.1]

  - id: "wall"
    shape: "box"
    position: [0.7, 0.0, 0.25]
    quat_xyzw: [0.0, 0.0, 0.0, 1.0]
    dimensions: [0.02, 0.5, 0.5]

  - id: "obstacle"
    shape: "sphere"
    position: [0.4, 0.2, 0.3]
    dimensions: [0.05]
